/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#C5F6ED",
        "tertiary-fixed": "#e2e2e3",
        "primary-fixed": "#e2e2e2",
        "surface-container": "#1e2024",
        "primary-fixed-dim": "#C5F6ED",
        "on-secondary-fixed-variant": "#46464a",
        "on-background": "#e2e2e8",
        "tertiary": "#c6c6c7",
        "on-primary": "#111318",
        "outline-variant": "#4c4546",
        "on-secondary-fixed": "#1b1b1f",
        "tertiary-fixed-dim": "#c6c6c7",
        "inverse-primary": "#5e5e5e",
        "on-secondary": "#303034",
        "on-surface-variant": "#cfc4c5",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0c0e12",
        "primary-container": "#000000",
        "primary": "#C5F6ED",
        "on-surface": "#e2e2e8",
        "surface-container-highest": "#333539",
        "surface-container-high": "#282a2e",
        "outline": "#988e90",
        "surface": "#111318",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#c7c6ca",
        "on-tertiary": "#2f3132",
        "on-tertiary-fixed-variant": "#454748",
        "error-container": "#93000a",
        "on-error": "#690005",
        "secondary-container": "#46464a",
        "inverse-on-surface": "#2f3035",
        "background": "#111318",
        "surface-bright": "#37393e",
        "secondary": "#c7c6ca",
        "on-tertiary-container": "#747576",
        "inverse-surface": "#e2e2e8",
        "surface-variant": "#333539",
        "surface-container-low": "#1a1c20",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed": "#e3e2e6",
        "on-secondary-container": "#b5b4b9",
        "tertiary-container": "#000000",
        "on-tertiary-fixed": "#1a1c1d",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-container": "#757575",
        "surface-dim": "#111318",
        "brand-primary": "#C5F6ED",
        "on-brand-primary": "#000000"
      },
      spacing: {
        "stack-sm": "8px",
        "unit": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter": "24px",
        "container-margin": "32px",
        "element-gap": "16px",
        "panel-padding": "24px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "display-xl": ["Inter"],
        "label-bold": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-xl": ["Inter"],
        "body-sm": ["Inter"],
        "label-lg": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "label-bold": ["14px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "14px", "fontWeight": "500" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
